### ISSUE TITLE
superordinate abstraction of Residues, Nucleotides, Ligands, etc. necessary

### ISSUE THREAD

**Issue by enauz** [cleberecht/singa#26]
- we need a superordinate abstraction of `Residues`, `Nucleotides`, `Ligands`, etc.
- they must declare a `StructuralEntityType` as well as possible exchanges
- this is a requirement for the Fit3D algorithm's position-specific-exchanges, substitution matrices, mutations, etc...

**Comment by cleberecht** [comment]
There are now Branch- and Leaf-Substructures. This definitely needs refinement. Will elaborate tomorrow.

**Comment by enauz** [comment]
- for the moment this is resolved, thanks Chris! @cleberecht
