### ISSUE TITLE
rename Residue & ResidueFamily to AminoAcid & AminoAcidFamily

### ISSUE THREAD

**Issue by enauz** [cleberecht/singa#37]
Suggestion: As for other types of molecules we should be stringent with the nomenclature, e.g.

- `Nucleotide` and `NucleotideFamily` are referring to the chemical species of nucleic acids **but** they are also residues of e.g. an aptamer
- this ambiguity is a reason to choose `AminoAcid` as explicit nomenclature

**Comment by cleberecht** [comment]
I agree! Just refactor it some time next week.

**Comment by cleberecht** [comment]
refactored in commit 9b5e2b5
