### ISSUE TITLE
add conversion between structure model and MoleculeGraph

### ISSUE THREAD

**Issue by fkaiserbio** [cleberecht/singa#77]
- should allow the conversion of `(Oak)Leafsubstructures` in `MoleculeGraph` objects
- needed for application of subgraph isomorphism detection algorithms
- further problem: cyclic dependency between structure/chemistry

**Comment by cleberecht** [comment]
implemented as of dabb7c8
aromatic ring systems can not be assigned double bonds deterministically, so take care
if you want to use the Molecule graph you have to import the chemistry package as well - if you really need it in structure, we can move it

**Comment by cleberecht** [comment]
resolved as of e0cc0ae
