### ISSUE TITLE
implement quaternion superimposition

### ISSUE THREAD

**Issue by fkaiserbio** [cleberecht/singa#78]
- an improvement of structure superimposition
- can be computed in better time: http://www.ncbr.muni.cz/~dave/SiteBinder/docs/thesis.pdf

**Comment by fkaiserbio** [comment]
- found another potentially valuable resource that is proposed to be super fast: https://www.ncbi.nlm.nih.gov/pubmed/20017124

**Comment by cleberecht** [comment]
implemented in latest stable release https://github.com/cleberecht/singa/releases/tag/v0.4.0
